/*
 * p2p File Sharer Rest API
 * This is the Rest API service which will be facilitating file download and health check capabilities.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package client.handler.auth;

public enum OAuthFlow {
    accessCode, implicit, password, application
}
