/*
 * p2p File Sharer Rest API
 * This is the Rest API service which will be facilitating file download and health check capabilities.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package client.api;

import client.handler.ApiException;
import client.model.ApiResponseDTO;
import java.io.File;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for FileDownloaderServiceApi
 */
@Ignore
public class FileDownloaderServiceApiTest {

    private final FileDownloaderServiceApi api = new FileDownloaderServiceApi();

    /**
     * Download a file by name
     *
     * Download a file by name
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void filesFileByNameGetTest() throws ApiException {
        String name = null;
        File response = api.filesFileByNameGet(name);

        // TODO: test validations
    }
}
