/*
 * p2p File Sharer Rest API
 * This is the Rest API service which will be facilitating file download and health check capabilities.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package client.api;

import client.handler.ApiException;
import client.model.HealthCheckResponseDTO;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for HealthCheckServiceApi
 */
@Ignore
public class HealthCheckServiceApiTest {

    private final HealthCheckServiceApi api = new HealthCheckServiceApi();

    /**
     * Check health of neibouring nodes
     *
     * Check health of neibouring nodes and remove them from the network if they are not working
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiHealthcheckGetTest() throws ApiException {
        HealthCheckResponseDTO response = api.apiHealthcheckGet();

        // TODO: test validations
    }
}
