/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.27).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package api;

import model.ApiResponseDTO;
import org.springframework.core.io.Resource;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;

@Validated
public interface FilesApi {

    @Operation(summary = "Download a file by name", description = "Download a file by name", tags={ "File Downloader Service" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "successful operation", content = @Content(mediaType = "application/octet-stream", schema = @Schema(implementation = Resource.class))),
        
        @ApiResponse(responseCode = "400", description = "Invalid request", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ApiResponseDTO.class))),
        
        @ApiResponse(responseCode = "404", description = "files not found", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ApiResponseDTO.class))),
        
        @ApiResponse(responseCode = "5XX", description = "Unexpected error", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ApiResponseDTO.class))) })
    @RequestMapping(value = "/files/file-by-name",
        produces = { "application/octet-stream", "multipart/form-data", "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Resource> filesFileByNameGet(@NotNull @Parameter(in = ParameterIn.QUERY, description = "file name that need to be downloaded from the peer" ,required=true,schema=@Schema()) @Valid @RequestParam(value = "name", required = true) String name);

}

